/*
 * File:   main.h
 * Author: luc
 *
 * Created on February 26, 2023, 11:37 AM
 */

#ifndef main_H
#include <16F690.h>
#include <math.h>
#define main_H
#fuses XT
#fuses NOPROTECT
#fuses BROWNOUT
#fuses NOWDT
#case
#define AMP 127
#define SIN_SAMPLES 32
#define TIMER2_PERIOD 255
#define MCU_FREQ_MHZ 2500000
#define T1_PRESCALER 1
#use delay (clock=10000000)
#use fast_io(A)
#use fast_io(B)

const unsigned int8 SinTable16[] ={ 
    AMP * 0,
    AMP * 0.2,
    AMP * 0.38,
    AMP * 0.56,
    AMP * 0.71,
    AMP * 0.83,
    AMP * 0.92,
    AMP * 0.98,
    AMP * 1.0,
    AMP * 0.98,
    AMP * 0.92,
    AMP * 0.83,
    AMP * 0.71,
    AMP * 0.56,
    AMP * 0.38,
    AMP * 0.20};

unsigned int sint( unsigned int& v);
void set_ctcss_period(unsigned int& p);
unsigned int16 update_dc_count;
unsigned int8 ctcss_sel;
int1 enableCTCSS;
int1 reverseBurst;
int1 RBFlag;
#define ENABLE_CTCSS_PIN PIN_B4
#define REVERSE_BURST_PIN PIN_B5

void initialize(void);

// Timer1 values for each CTCSS frequency when running at
// FOSC = 10MHz

const unsigned int16 CTCSS_T1_FREQ[] = {
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/67,    
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/69.3,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/71.9,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/74.4,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/77,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/79.7,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/82.5,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/85.4,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/88.5,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/91.5,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/94.8,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/97.4,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/100,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/103.5,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/107.2,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/110.9,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/114.8,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/118.8,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/123,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/127.3,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/131.8,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/136.5,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/141.3,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/146.2,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/151.4,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/156.7,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/162.2,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/167.9,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/173.8,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/179.9,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/186.2,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/192.8,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/203.5,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/206.5,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/210.7,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/218.1,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/225.7,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/229.1,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/233.6,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/241.8,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/250.3,
    MCU_FREQ_MHZ/SIN_SAMPLES/T1_PRESCALER/254.1,
};
#endif

